[package]
name = "client"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.12", features = ["full"] }
futures = "0.3"
serde = { version = "1.0.0", features = ["derive"] }
toml = "0.5"
