[package]
name = "rust_server"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["tls", "json", "uuid"] }
mongodb = { version = "2.0.0", features = ["bson-uuid-0_8"] }
uuid = { version = "0.8.2", features = ["v4"] }
serde = "1.0.0"
delegate = "0.6.1"
